
  version: '3.8'

  services:
    mysqldb:
      image: mysql:8.3.0
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_DATABASE=projet_foyer
      ports:
        - 3306:3306
      volumes:
        - dbvolume:/var/lib/mysql
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 10s
        timeout: 5s
        retries: 3

    app:
      depends_on:
        - mysqldb
      image: selmisouheil/backend-spring:1.0.0
      restart: on-failure
      ports:
        - 8089:8089
      environment:
          SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:mysql://mysqldb:3306/projet_foyer?createDatabaseIfNotExist=true",
              "spring.datasource.username": "root",
              "spring.datasource.password": "",
              "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
              "spring.jpa.hibernate.ddl-auto": "update"
            }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
      tty: true
    volumes:
      dbvolume:
